server:
  port: 7072

spring:
  application:
    name: doseo_book

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.107.166.217:3306/chomini?serverTimezone=Asia/Seoul
    url: jdbc:mysql://192.168.0.27:3306/chomini?serverTimezone=Asia/Seoul
    username: mytest
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
